# Netlify Configuration
[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://your-backend-domain.com"
  REACT_APP_SOCKET_URL = "https://your-backend-domain.com"
